### ISSUE TITLE
Initial performance assesment

### ISSUE THREAD

**Issue by nbarriga** [ISILab-Utalca/LevelBuildingSidekick#2]

**Comment by RosenkreuzAlice** [comment]
### **== ERRORES MAYORES ==**
1.- Al intentar ver behaviors en la layer exterior, salta un error ArgumentNullException - SimplePalette, línea 170.
	- Saltó al haber una layer interior y una exterior activas.
2.- Al abrir la aplicación e intentar crear una layer interior, esta no se actualiza en la lista de layers; sólo puede actualizarse borrando algo.
	- Al agregar una layer, esta se crea, pero no se muestra en la lista. Aparece el siguiente error: "InvalidCastException: Specified cast is not valid."
3.- Ctrl-Z y Ctrl-Y se demoran más de medio segundo en ejecutarse. A veces más de un segundo.
4.- Añadir habitaciones en las layers interiores es lento, y optimizarlas es aún más lento.
	- Si la layer es demasiado compleja, el algoritmo se volverá exponencialmente grande y no acabará de buscar nunca.
5.- Hay un error en la generación de exteriores, relacionado a los bundles (la sección de "Assets" está vacía), que provoca que no se genere nada.
	- El error debe estar en los bundles utilizados.
6.- El dropdown de preset en el asistente de población no está mostrando las opciones que debería.
7.- Error al intentar borrar conexiones de quests cuando no las hay.
8.- Hay un error de ortografía en la sección de "Behaviours" exteriores. (Exteriror)
	- De hecho, "Behaviour" es poco estándar en comparación con "Behavior"; usar "Behavior" en su lugar.
~~9.- El botón de "execute" tiene problemas juntando habitaciones si estas están demasiado separadas.~~
El error estaba relacionado a una falta de conexiones entre habitaciones. Aún así, la cantidad de tiempo que la aplicación despedicia en habitaciones vacías sin conectar entre sí es inaceptable.
10.- Tras usar el botón de "execute", se pueden dibujar habitaciones encima de sí mismas, con muros incluídos.
11.-. Según el Test Runner, los elementos "Save_And_Load_Bundle_Tilemap" y "Save_And_Load_Population_Layer" tienen errores; la información de los mencionados no se está serializando correctamente.

### **== ERRORES MENORES ==**
a.- Agregar layers, tanto exteriores e interiores, debería ser más rápido. Debido al hecho de que están funcionalmente vacías, debería ser instantáneo.
b.- Buscar una forma de comunicar la información de la aplicación mejor a los usuarios.

### **==     CAMBIOS     ==**
a.- Modificar/simplificar sistema de módulos que relaciona habitaciones y tiles. Aunque simplifique la usabilidad para usuarios hasta cierto punto, ralentiza los algoritmos para la inteligencia artificial que los maneje.
b.- Explorar si mantener los Bundles como Bundles o cambiarlos a MonoBehaviors.

### **==   SUGERENCIAS   ==**
- Agregar tooltips a variables importantes.
- Aplicación no es genérica en sus propósitos; explorar opciones al respecto. (¿Recomendaciones? ¿Soporte para modificaciones?)
- Trabajar en la complejidad de presets.
- Hacer el plugin más "user friendly" por medio de darle más feedback al usuario (tooltips para optimización de niveles y cosas por el estilo).
- Agregar (si se puede) un sistema de drag and drop en las ventanas laterales (3D, Quests, Layers).
- Si se usa el pincel en una layer exterior sin que haya habitaciones creadas, podría crearse una habitación nueva automáticamente para que el trazo no se desperdicie.

### **== IDEAS: DOCUMENTACIÓN ==**
- Obsidian (Markdown) para documentar; documentación integrada con GitHub.
- Añadir botones de información a cada objeto con una interfaz personalizada para facilidad de información.
