### ISSUE TITLE
Initial usability assessment

### ISSUE THREAD

**Issue by nbarriga** [ISILab-Utalca/LevelBuildingSidekick#3]

**Comment by rothbilly** [comment]
# Elementos de usabilidad (WIP)
Lista de elementos detectados que pueden afectar a la experiencia de usuario y posibles mejoras a la experiencia actual.

## Aun  WIP
- Sistema de quest esta apenas
- 


## Mejoras Visuales/UI
- Los botones de la columna deberían mostrarse en modo `Toggle` para saber que panel esta activo o no. #4 
- El icono de `Layer` y` Modulos `es demasiado similar.
- Los iconos podrian ser verctoriales. #6 

## Mejoras de experiencia
- Crear una nueva capa en el menú de `Layers` debería seleccionar la capa ya creada
- permitir renombrar las zonas en el menu de `Behavior` en el contexto de una capa `Interior` 
- Usar click derecho para borrar segun que herramienta. #5 
- Mostar `Hover` sobre los Modulos que se pueden editar.
- Permitir estilos funciones en modo light/dark #8 o crear un tema unico para la herramienta

## Optimizaciones y errores detectados
- Seleccionar la pestaña de ´Behaviors´ tarda mas de 0.4s en ser seleccionado.
- Cambiar de capa tarda mas de 0.4s  para ser una acción tan simple

## Sugerencias (New Features)
- Modification: Permitir mover y reorganizar los botones del la columna #7 
- Feature: Tener un Menu/Wizzard para crear bundles de assets
- Feature: Lista de bundles creados y faciles de inspeccionar
- Feature: Crear un Validator para los bundles que se han creado.
- Feature: Notificador tipo Helper, para saber que falta, actua mas como un validator, tutor, por ejemplo si no tienes seleccionada una capa
- Feature: Tag Manager que facilite crear y editar tags

La mayoría de sugerencias van para el manejo y la revisión de los bundles creados, ya que todo lo que involucra aplicar un estilo a un mapa, esta oculto o hay poca información.
